Develop
yoseffyy/node-file-systeo-client-service pull request #1
Opened 2020-03-29 07:19 UTC by yoseffyy

2020-03-29 09:15 UTC, yonatandt requested changes
You need to implement the grpc-client differently. I will elaborate on the phone.

2020-03-29 09:15 UTC, yonatandt commented on .gitignore
> +node_modules/
ignore the dist folder as well

2020-03-29 09:15 UTC, yonatandt commented on Dockerfile
> +COPY ./build.config.json ./../config.json
You can export the config from a `.ts` file so you won't need to copy the file itself.

2020-03-29 09:15 UTC, yonatandt commented on build.config.json
> +    "server_port": "4040",
Our standard port for services is usually 8080.

2020-03-29 09:15 UTC, yonatandt commented on docker-compose.yml
> +            - "4040:4040"
Our external port of services starts from 8080 and goes up by 1 for any additional service.

2020-03-29 09:15 UTC, yonatandt commented on package.json
> +    "@types/mongoose": "^5.5.34",
These should be in the `devDependencies`

2020-03-29 09:15 UTC, yonatandt commented on src/server.ts
> + });
If you want to wait for the App's constructor to finish, make it async. Don't just guess with `sleep`.

2020-03-29 09:15 UTC, yonatandt commented on src/server.ts
> +    var stop = new Date().getTime();
don't use var

2020-03-29 09:15 UTC, yonatandt commented on src/server.ts
> +    5000
Don't you use the `port` from the config?

2020-03-29 09:15 UTC, yonatandt commented on src/server.ts
> +}
You have an npm package called [morgan](https://www.npmjs.com/package/morgan) for that.

2020-03-29 09:15 UTC, yonatandt commented on src/controllers/file.controller.ts
> +        this.router.put('/', this.update);
You should give the `fileID` in the params.

2020-03-29 09:15 UTC, yonatandt commented on src/controllers/file.controller.ts
> +                res.send(error);
In case of an error, you should return a corresponding status code.

2020-03-29 09:15 UTC, yonatandt commented on src/controllers/file.controller.ts
> +        console.log(data)
redundant `console.log`

2020-03-29 09:15 UTC, AllKinds commented on src/interfaces/file.interface.ts
> +    napathme: string;
What?

2020-03-29 09:15 UTC, AllKinds commented on src/repositories/file.repsitory.ts
> +//   });
Delete these lines.

2020-03-30 07:25 UTC, yoseffyy commented on src/interfaces/file.interface.ts
> +    napathme: string;
na path me

2020-03-30 07:25 UTC, yoseffyy commented on src/interfaces/file.interface.ts
> +    napathme: string;
כנראה גררתי לשם בטעות

2020-03-30 07:26 UTC, yoseffyy commented on src/server.ts
> + });
זה בשביל docker-compose שלא יפעל ליפני ה- server

2020-03-30 11:17 UTC, merged